{% set name = "pyproject-metadata" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypa/pyproject-metadata/archive/refs/tags/{{ version }}.tar.gz
  sha256: e23f57ee2c83e364badf6503a21e0d80db3440afe520b211c1d1e9060010f0f8

build:
  skip: True # [py<312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python
    - flit-core
  run:
    - packaging >=19.0
    - python
    - typing_extensions  # [py<38]

test:
  imports:
    - pyproject_metadata
  commands:
    - pip check
  requires:
    - pip
    - pytest >=6.2.4
    - tomli >=1.0.0  #  [py<311]

about:
  home: https://github.com/pypa/pyproject-metadata
  summary: PEP 621 metadata parsing
  description: |
    This project does not implement the parsing of pyproject.toml containing PEP 621 metadata.
    Instead, given a Python data structure representing PEP 621 metadata (already parsed),
    it will validate this input and generate a PEP 643-compliant metadata file (e.g. PKG-INFO).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pypa/pyproject-metadata
  doc_url: https://github.com/pypa/pyproject-metadata/blob/main/README.md

extra:
  recipe-maintainers:
    - gforsyth
